Feature/post
Like-Lion-NSU/Elementary_School pull request #19
Opened 2024-04-19 15:38 UTC by changhyun-jang

## #️⃣연관된 이슈 번호
#16 

## 📝작업 내용
- 레이어별 가질 책임에 대해 생각하며 Post CRUD와 관련된 코드를 개선하였습니다.

2024-04-20 10:04 UTC, songhyeon99 commented
모든 주석은 지워주세요!

2024-04-20 11:36 UTC, songhyeon99 requested changes

2024-04-25 13:02 UTC, changhyun-jang commented on BE/school/src/main/java/thisisus/school/post/service/PostServiceImpl.java
> +        postRepository.save(post);
리뷰를 반영하여 dirty checking을 통한 코드 간략화를 진행했습니다.

2024-04-25 13:02 UTC, changhyun-jang commented on BE/school/src/main/java/thisisus/school/post/controller/PostController.java
> +@RequestMapping
api 추가 하였습니다.

2024-04-25 13:05 UTC, changhyun-jang commented on BE/school/src/main/java/thisisus/school/post/domain/Post.java
> +    public void update(PostUpdateRequest postRequest) {
https://myeongdev.tistory.com/m/81
블로그를 참고하여 수정하였습니다!

2024-05-08 08:48 UTC, merged